FROM python:3.9-slim

#RUN apk update && apk add gcc g++ linux-headers build-base py3-pip bash curl

RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install -q Flask==2.0.1 requests==2.18.4 
RUN pip3 install opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp opentelemetry-instrumentation-flask opentelemetry-instrumentation-requests opentelemetry-propagator-b3
RUN mkdir /code
ADD ./service.py /code
ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT ["/bin/sh", "/usr/local/bin/start_service.sh"]
